// This file is generated by Slice Machine. Update with care!

import Mynd from './Mynd/index.tsx';
import Texti from './Texti/index.tsx';
import Titill from './Titill/index.tsx';

export {
	Mynd,
	Texti,
	Titill,
};

export const components = {
	mynd: Mynd,
	texti: Texti,
	titill: Titill,
};
