// This file is generated by Slice Machine. Update with care!

import Mynd from './Mynd';
import Texti from './Texti';
import Titill from './Titill';
import Vidburdir from './Vidburdir';
import Vidburdur from './Vidburdur';

export {
	Mynd,
	Texti,
	Titill,
	Vidburdir,
	Vidburdur,
};

export const components = {
	mynd: Mynd,
	texti: Texti,
	titill: Titill,
	vidburdir: Vidburdir,
	vidburdur: Vidburdur,
};
