// This file is generated by Slice Machine. Update with care!

import Embedded from './Embedded';
import IndexForm from './IndexForm';
import MargarMyndir from './MargarMyndir';
import Mynd from './Mynd';
import Texti from './Texti';
import Titill from './Titill';
import Listi from './Listi';

export {
	Embedded,
	IndexForm,
	Listi,
	MargarMyndir,
	Mynd,
	Texti,
	Titill,
};

export const components = {
	embedded: Embedded,
	index_form: IndexForm,
	listi: Listi,
	margar_myndir: MargarMyndir,
	mynd: Mynd,
	texti: Texti,
	titill: Titill,
};
